<tr>
    <td class="td_footer" align="center"><a href="/" class="footer">What-time.info</a> - exact time for any city</td>
</tr>
</tbody>
</table>


<script src="/js/jquery.min.js"/></script>
<script src="/js/jquery-ui.js"/></script>
<script src="/js/jquery.ui.autocomplete.html.js"/></script>
<script src="https://unpkg.com/leaflet@1.9.2/dist/leaflet.js" integrity="sha256-o9N1jGDZrf5tS+Ft4gbIK7mYMipq9lqpVJ91xHSyKhg=" crossorigin=""></script>
<script src="/js/whattime.js?t=<?=time()?>"/></script>
</body>
</html>